### ISSUE TITLE
RuntimeError: DataLoader worker (pid 19597) is killed by signal: Killed

### ISSUE THREAD

**Issue by slc688888** [hezhangsprinter/DCPDN#12]
when I run train.py , I got en error. Is my memory too little？My memory is 16G and Gpu memory is 8G
Details：
Traceback (most recent call last):
  File "train.py", line 210, in <module>
    val_target_cpu, val_input_cpu = val_target_cpu.float().cuda(), val_input_cpu.float().cuda()
  File "/home/littlemonster/anaconda3/envs/pic/lib/python2.7/site-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/home/littlemonster/anaconda3/envs/pic/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 175, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 19597) is killed by signal: Killed.

Look forward to your rely！

**Comment by Devin97** [comment]
Getting the same error ... don't understand what is causing this..

**Comment by zhaoxin111** [comment]
set workers 0

**Comment by Devin97** [comment]
It worked thanks!!
