### ISSUE TITLE
demo.py   error

### ISSUE THREAD

**Issue by zjujiangxin** [hezhangsprinter/DCPDN#54]
Hi, I stopped at the error message while executing demo.py

Traceback (most recent call last):
  File "demo.py", line 231, in <module>
    x_hat, tran_hat, atp_hat, dehaze2= netG(input)
  File "/home/dl/anaconda3/envs/dcpdn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/dl/A420F0F420F0CE74/jx/DCPDN/dehaze22.py", line 565, in forward
    tran=self.tran_dense(x)
  File "/home/dl/anaconda3/envs/dcpdn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/dl/A420F0F420F0CE74/jx/DCPDN/dehaze22.py", line 470, in forward
    x0=self.pool0(self.relu0(self.norm0(self.conv0(x))))
  File "/home/dl/anaconda3/envs/dcpdn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dl/anaconda3/envs/dcpdn/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/home/dl/anaconda3/envs/dcpdn/lib/python3.6/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: Given groups=1, weight[64, 3, 7, 7], so expected input[1, 4, 497, 513] to have 3 channels, but got 4 channels instead

can you help me solve this
thanks for reading

**Comment by Clearlove4396** [comment]
Have you solved the problem？
