### ISSUE TITLE
train error /KeyError: 'module name can\'t contain ".", got: layer2.leakyrelu'

### ISSUE THREAD

**Issue by gyx-tail** [hezhangsprinter/DCPDN#64]
When I run the train.py,show this
Traceback (most recent call last):
  File "train.py", line 118, in <module>
    netG = net.dehaze(inputChannelSize, outputChannelSize, ngf)
  File "/mnt/e/PycharmProject/DCPDN-master/models/dehaze22.py", line 665, in __init__
    self.tran_est=G(input_nc=3,output_nc=3, nf=64)
  File "/mnt/e/PycharmProject/DCPDN-master/models/dehaze22.py", line 216, in __init__
    layer2 = blockUNet(nf, nf*2, name, transposed=False, bn=True, relu=False, dropout=False)
  File "/mnt/e/PycharmProject/DCPDN-master/models/dehaze22.py", line 56, in blockUNet
    block.add_module('%s.leakyrelu' % name, nn.LeakyReLU(0.2, inplace=True))
  File "/home/gyx1999/anaconda3/envs/pytorchgpu/lib/python3.8/site-packages/torch/nn/modules/module.py", line 380, in add_module
    raise KeyError("module name can't contain \".\", got: {}".format(name))
KeyError: 'module name can\'t contain ".", got: layer2.leakyrelu'
How can I solve this problem

**Comment by DMNQYQ** [comment]
请问你解决了吗 我也遇到了这样的问题

**Comment by suannaige** [comment]
> 请问你解决了吗 我也遇到了这样的问题

dahaze22中，block module 把里面的参数%d后面的点删掉就行，

**Comment by ZhuLiangyu123** [comment]
> 请问你解决了吗 我也遇到了这样的问题

将%s.leakyrelu' % name修改为%s_leakyrelu' % name即可。
