### ISSUE TITLE
运行train发现这么多问题

### ISSUE THREAD

**Issue by wowwowya** [hezhangsprinter/DCPDN#65]
Traceback (most recent call last):
  File "E:\DCPDN-master\DCPDN-master\train.py", line 76, in <module>
    dataloader = getLoader(opt.dataset,
  File "E:\DCPDN-master\DCPDN-master\misc.py", line 64, in getLoader
    dataloader = torch.utils.data.DataLoader(dataset, 
  File "C:\ProgramData\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 351, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "C:\ProgramData\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by jokerDYH** [comment]
加载数据不对
