### ISSUE TITLE
Cannot download VGG16.t7

### ISSUE THREAD

**Issue by AZHAIxp** [hezhangsprinter/DCPDN#67]
When I run the code with python train.py --dataroot ./facades/train512 --valDataroot ./facades/test512 --exp ./checkpoints_new --netG ./demo_model/netG_epoch_8.pth, the following issue arises.

Traceback (most recent call last):
  File "train.py", line 197, in <module>
    utils.init_vgg16('./models/')
  File "/home/deep/1-POJECT/zpc/DCPDN-master/myutils/utils.py", line 90, in init_vgg16
    vgglua = load_lua(os.path.join(model_folder, 'vgg16.t7'))
  File "/home/deep/anaconda3/envs/zpc-dcpdn/lib/python3.6/site-packages/torch/utils/serialization/read_lua_file.py", line 606, in load_lua
    return reader.read()
  File "/home/deep/anaconda3/envs/zpc-dcpdn/lib/python3.6/site-packages/torch/utils/serialization/read_lua_file.py", line 577, in read
    typeidx = self.read_int()
  File "/home/deep/anaconda3/envs/zpc-dcpdn/lib/python3.6/site-packages/torch/utils/serialization/read_lua_file.py", line 474, in read_int
    return self._read('i')
  File "/home/deep/anaconda3/envs/zpc-dcpdn/lib/python3.6/site-packages/torch/utils/serialization/read_lua_file.py", line 465, in _read
    result = struct.unpack(fmt, self.f.read(sz))
struct.error: unpack requires a buffer of 4 bytes

I spent a long time on this but it didn't work out, what should I do to fix this problem.

Thanks!

**Comment by 11140408coups** [comment]
Hello, I met the same problem with you, in my opinion is because http://cs.stanford.edu/people/jcjohns/fast-neural-style/models/vgg16.t7 has does not exist as a result, do you have this problem solved?
