### ISSUE TITLE
about pytorch's version

### ISSUE THREAD

**Issue by KosumosuL** [hezhangsprinter/DCPDN#8]
after changing the version of pytorch to 0.3.1
the following problem occurred:
```
Traceback (most recent call last):
  File "demo.py", line 128, in <module>
    netG = net.dehaze(inputChannelSize, outputChannelSize, ngf)
  File "/data2/zhangzhengxi4047/dcpdn.pytorch/DCPDN/dehaze22.py", line 540, in __init__
    self.tran_dense=Dense()
  File "/data2/zhangzhengxi4047/dcpdn.pytorch/DCPDN/dehaze22.py", line 411, in __init__
    haze_class = models.densenet121(pretrained=True)
  File "build/bdist.linux-x86_64/egg/torchvision/models/densenet.py", line 27, in densenet121
  File "build/bdist.linux-x86_64/egg/torchvision/models/densenet.py", line 213, in __init__
AttributeError: 'module' object has no attribute 'kaiming_normal_'
```
what should i do?

**Comment by KosumosuL** [comment]
solved

**Comment by Neobe** [comment]
Hello，I meet the same problem，can you tell me how to solve this?

**Comment by KosumosuL** [comment]
Sorry for my forgetting the specific solution, but it since like I solved
this problem by re-installing the pytorch from github.

2018-07-26 14:40 GMT+08:00 Neobe <notifications@github.com>:
